image: Visual Studio 2019
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable --version 4.0.0

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - nuget restore src\Cogito.Oracle.ManagedDataAccess.sln
  - dotnet restore src\Cogito.Oracle.ManagedDataAccess.sln

build:
  verbosity: minimal
  project: src\Cogito.Oracle.ManagedDataAccess.sln

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.Oracle.ManagedDataAccess
