<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageProjectReference Include="..\Cogito.Oracle.ManagedDataAccess\Cogito.Oracle.ManagedDataAccess.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
        <PackageProjectReference Include="..\Cogito.Oracle.ManagedDataAccess.Core\Cogito.Oracle.ManagedDataAccess.Core.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
    </ItemGroup>

</Project>
